---
title: "Clustering in R"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

An incomplete lesson, copied from PCA lesson on 2016-11-15

##References:

+ https://www.r-bloggers.com/k-means-clustering-in-r/
+ http://www.statmethods.net/advstats/cluster.html
+ https://stat.ethz.ch/R-manual/R-devel/library/stats/html/kmeans.html
+ http://stackoverflow.com/questions/15376075/cluster-analysis-in-r-determine-the-optimal-number-of-clusters
+ [Wikipedia entry for the various ways of determining the optimal number of clusters](https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set)
+ [Programmatically identifying the "elbow"](http://stackoverflow.com/questions/2018178/finding-the-best-trade-off-point-on-a-curve)


##Clustering with K-means

```{r}
# Scale data & drop species column
otter.scaled <- scale(x = otter[, -1])
wss <- numeric(10)
for (i in 1:10) {
  kmeans.fit <- kmeans(x = otter.scaled, centers = i, nstart = 10)
  wss[i] <- kmeans.fit$tot.withinss
}
plot(x = c(1:length(wss)), y = wss, xlab = "Number of clusters, K", ylab = "Total within SS", type = "b")

# Percentage of variance explained is the ratio of the between-group variance to the total 
# variance, also known as an F-test. A slight variation of this method plots the curvature 
# of the within group variance. https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set
# 

```

Abstracting the number of clusters to analyze
```{r}
```

Apply "Elbow" method based on percentage of variance explained
```{r}
# Advanced
```

See how clustering aligned with species
```{r}
# Run kmeans again for K = 4, to get clustering info
otter.k.4 <- kmeans(x = otter.scaled, centers = 4, nstart = 10)
otter.clusters <- data.frame(otter, cluster = otter.k.4$cluster)
assignments <- table(otter.clusters$species, otter.clusters$cluster)
assignments

```
