---
title: "Heatmaps in R"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

A worked example of making heatmaps in R with the `ggplot` package, as well as some data wrangling to easily format the data needed for the plot.

#### Learning objectives
1. Manipulate data into a 'tidy' format
2. Visualize data in a heatmap
3. Become familiar with `ggplot` syntax for customizing plots

## Heatmaps & data wrangling
Heatmaps are a great way of displaying three-dimensional data in only two dimensions. But how can we easily translate tabular data into a format for heatmap plotting? By taking advantage of "data munging" and graphics packages, heatmaps are relatively easy to produce in R. 

***

## Getting started

***

## [TOPIC ONE]
Need to have data set with an id column and another column we want to preserve, but not the id column

***

## [TOPIC TWO]

```{r}
library("tidyr")
library("ggplot2")
mine.data <- read.csv(file = "data/mine-microbe-class-data.csv")

mine.long <- gather(data = mine.data, key = Class, value = Abundance, -c(1:3))
# mine.long <- gather(data = mine.data, key = Class, value = Abundance, -Site, -Depth, -Sample.name)

mine.long$log.abundance <- log10(mine.long$Abundance)
mine.long$sqrt.abundance <- sqrt(mine.long$Abundance)

mine.long$Sample.name <- factor(mine.long$Sample.name, levels = c("1-S", "2-S", "3-S", "1-M", "2-M", "3-M", "2-B", "3-B"))

mine.heatmap <- ggplot(data = mine.long, aes(x = Sample.name,
                                             y = Class,
                                             fill = sqrt.abundance)) +
  geom_tile() +
  scale_fill_gradient(name = "Sqrt(Abundance)",
                      low = "#222222",
                      high = "#FFFFFF") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_text(size = 8))


mine.heatmap



mine.data <- read.csv(file = "data/mine-microbe-order-data.csv")

mine.long <- gather(data = mine.data, key = Order, value = Abundance, -c(1:3))
# mine.long <- gather(data = mine.data, key = Order, value = Abundance, -Site, -Depth, -Sample.name)

mine.long$Log.abundance <- log10(mine.long$Abundance)
mine.long$sqrt.abundance <- sqrt(mine.long$Abundance)

mine.long$Sample.name <- factor(mine.long$Sample.name, levels = c("1-S", "2-S", "3-S", "1-M", "2-M", "3-M", "2-B", "3-B"))

mine.heatmap <- ggplot(data = mine.long, aes(x = Sample.name,
                                             y = Order,
                                             fill = Log.abundance)) +
  geom_tile() +
  scale_fill_gradient(name = "Log(Abundance)",
                      low = "#222222",
                      high = "#FFFFFF") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_text(size = 8))


mine.heatmap




```

***

## Additional resources

+ [resource one](url-one)
+ [resource two](url-two)

***

<a href="index.html">Back to learn-r main page</a>
  
Questions?  e-mail me at <a href="mailto:jcoliver@email.arizona.edu">jcoliver@email.arizona.edu</a>.