---
title: "LESSON TITLE"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: default
  pdf_document: default
---

Want to combine the visualization of quantitative data with clustering algorithms? Unsatisfied with the options provided by the base R packages? In this hands-on workshop, we'll use the `ggendro` package for R to make publication-quality graphics.

+ Consider the `ggdendro` package? See: https://stackoverflow.com/questions/6673162/reproducing-lattice-dendrogram-graph-with-ggplot2
+ [ggdendro page](https://cran.r-project.org/web/packages/ggdendro/vignettes/ggdendro.html)

0. What are the data? (the otter data?)
1. Clustering approach (e.g. `hclust`)
2. Drawing just a cluster
3. Drawing just a heatmap (`geom_tile`); individuals on Y, measurement on X

#### Learning objectives
1. one
2. two
3. three

## [DESCRIPTION OR MOTIVATION; 2-4 sentences that would be used for an announcement]

***

## Getting started

***

## [TOPIC ONE]

***

## [TOPIC TWO]

***

## Additional resources

+ [resource one](url-one)
+ [resource two](url-two)

***

<a href="index.html">Back to learn-r main page</a>
  
Questions?  e-mail me at <a href="mailto:jcoliver@email.arizona.edu">jcoliver@email.arizona.edu</a>.