---
title: "Dynamic reports with quarto"
author: "Jeff Oliver"
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r library-check, echo = FALSE, results = "hide"}
#| output: false

libs <- c("knitr", "quarto")
libs_missing <- libs[!(libs %in% installed.packages()[, "Package"])]
if (length(libs_missing) > 0) {
  for (l in libs_missing) {
    install.packages(l)
  }
}
```

An introduction to using the `quarto` package in R to produce reproducible, 
dynamic reports. 

# TODO: Add link to knitr lesson?

#### Learning objectives

After this lesson, learners should be able to:

1. Install and use third-party packages for R
2. Become familar with R Markdown syntax
3. Write dynamic reports including code and visualizations

## [DESCRIPTION OR MOTIVATION; 2-4 sentences that would be used for an announcement]

## Setup

### Install libraries

The R program has a bunch of tools that come with the initial installation, but 
we are going to use some add-ons for this lesson. In R, these "add-ons" are 
called packages, and we have to install them in order to use them on our 
machine.

# TODO: Install quarto and knitr

### Create a project

Next we need to setup our development environment. Open RStudio and create a 
new project via:

+ File > New Project...
+ Select 'New Directory'
+ For the Project Type select 'Quarto Project'
+ For Directory name, call it something like "chapter-1" (without the quotes)
+ For the subdirectory, select somewhere you will remember (like "My Documents" 
or "Desktop")

***

## [TOPIC ONE Introduction to markdown syntax]

# TODO: Look at default file and describe parts (text + code)

# TODO: Render the doc

# TODO: A couple of formatting things?

***

## [TOPIC TWO Code chunks]

Make a plot

Run some stats (hiding the output)

***

## [TOPIC THREE Taking code into text]

Stuff like putting r2 values in text

***

## [TOPIC FOUR Template files (doc)]

***

## Additional resources

+ [resource one](url-one)
+ [resource two](url-two)
+ A [PDF version](https://jcoliver.github.io/learn-r/lesson-name.pdf) of this lesson

***
