project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - schedule.qmd
    - resources.qmd
    - 000-setup-instructions.qmd
    - 001-basic-graphing.qmd
    - 002-intro-stats.qmd
    - 003-intro-multivariate.qmd
    - 004-intro-ggplot.qmd
    - 005-intro-knitr.qmd
    - 006-heatmaps.qmd
    - 007-intro-functional-programming.qmd
    - 008-ggplot-dendrograms-and-heatmaps.qmd
    - 009-expression-heatmaps.qmd
    - 010-github.qmd
    - 011-species-distribution-models.qmd
    - 012-intro-tidyverse.qmd
    - 014-intro-summarizing-visualizing.qmd
    - 016-intro-shiny.qmd
    - 017-open-street-map.qmd
    - 018-ml-regression.qmd

website:
  title: "learn-r"
  site-path: "/learn-r/"
  google-analytics: 
    tracking-id: "G-EF6ZJH0577"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "R Lessons"
        menu: 
          - 001-basic-graphing.qmd
          - 002-intro-stats.qmd
          - 003-intro-multivariate.qmd
          - 004-intro-ggplot.qmd
          - 005-intro-knitr.qmd
          - 006-heatmaps.qmd
          - 007-intro-functional-programming.qmd
          - 008-ggplot-dendrograms-and-heatmaps.qmd
          - 009-expression-heatmaps.qmd
          - 010-github.qmd
          - 011-species-distribution-models.qmd
          - 012-intro-tidyverse.qmd
          - 014-intro-summarizing-visualizing.qmd
          - 016-intro-shiny.qmd
          - 017-open-street-map.qmd
          - 018-ml-regression.qmd
      - href: schedule.qmd
        text: Schedule
      - href: resources.qmd
        text: Additional Resources
  page-footer: 
    left: 
      - text: Copyright 2024, Jeffrey Oliver
    center: 
      - text: CC BY 4.0 Deed
        href: https://creativecommons.org/licenses/by/4.0/
    right: 
      - icon: github
        href: https://github.com/jcoliver

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
  pdf: default
