---
title: Schedule
format: # to suppress pdf link
  html:
    toc: false
---

## Tentative schedule of upcoming sessions

| Day | Month | Workshop                                                     |
|:---:|:-----:|:-------------------------------------------------------------|
| 18  | Sep   | Open lab                                                     |
| 25  | Sep   | Open lab                                                     |
| 01  | Aug   | Open lab **AND** R - Data Visualization with ggplot          |
| 08  | Aug   | Open lab                                                     |
| 15  | Aug   | Open lab                                                     |
| 22  | Aug   | Open lab **AND** Geospatial Data Wrangling - QGIS            |
| 29  | Aug   | Open lab **AND** Python - Introduction to data visualization |
| 06  | Oct   | Open lab **AND** R - Introduction to statistics in R         |
| 13  | Oct   | Open lab                                                     |
| 20  | Oct   | Open lab **AND** Geospatial Data Wrangling - ArcGIS Online   |
| 27  | Oct   | Open lab                                                     |
| 03  | Nov   | Open lab **AND** Python - Introduction to linear regression  |
| 10  | Nov   | Open lab **AND** Geospatial Terrain Analysis - QGIS          |
| 17  | Nov   | Open lab **AND** R - Using Git and GitHub with RStudio       |
| 24  | Nov   | Open lab                                                     |
| 01  | Dec   | Open lab **AND** Geospatial Terrain Analysis - ArcGIS Online |
| 08  | Dec   | Open lab **AND** R - Introduction to neural networks in R    |
| 15  | Dec   | Open lab                                                     |
| 22  | Dec   | _No lab this day_                                            |
| 29  | Dec   | _No lab this day_                                            |


All sessions will be 9-11 AM on Tuesday morning (MST) in hybrid format: we will 
be in the Data Studios of the [Main Library](https://lib.arizona.edu/study/spaces/data-studio) 
and running a concurrent Zoom session.

For information on connecting to online sessions, reach out to us on the r 
channel of the [UA Data Science Slack workspace](https://jcoliver.github.io/uadatascience-slack/) 
or contact Jeff Oliver.

To get the most out of these workshops, participants should bring a laptop with 
[R and RStudio installed](https://jcoliver.github.io/learn-r/000-setup-instructions.html).

If you have questions about the schedule, or are interested in learning about a 
particular topic in R, contact Jeff Oliver at [jcoliver@arizona.edu](mailto:jcoliver@arizona.edu?subject=R%20workshop%20inquiry).
