<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jeff Oliver">
<meta name="dcterms.date" content="2024-05-08">

<title>learn-r - Introduction to Multivariate Statistics in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EF6ZJH0577"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-EF6ZJH0577', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">learn-r</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-lessons" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">R Lessons</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-lessons">    
        <li>
    <a class="dropdown-item" href="./001-basic-graphing.html" rel="" target="">
 <span class="dropdown-text">Introduction to R Graphing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./002-intro-stats.html" rel="" target="">
 <span class="dropdown-text">Introduction to R Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./003-intro-multivariate.html" rel="" target="">
 <span class="dropdown-text">Introduction to Multivariate Statistics in R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./004-intro-ggplot.html" rel="" target="">
 <span class="dropdown-text">Introduction to data visualization with ggplot</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./005-intro-knitr.html" rel="" target="">
 <span class="dropdown-text">Dynamic reports with knitr</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./006-heatmaps.html" rel="" target="">
 <span class="dropdown-text">Heatmaps in R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./007-intro-functional-programming.html" rel="" target="">
 <span class="dropdown-text">Introduction to Functional Programming</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./008-ggplot-dendrograms-and-heatmaps.html" rel="" target="">
 <span class="dropdown-text">Clusters and Heatmaps</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./009-expression-heatmaps.html" rel="" target="">
 <span class="dropdown-text">Heatmaps - the gene expression edition</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./010-github.html" rel="" target="">
 <span class="dropdown-text">Git and GitHub in RStudio</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./011-species-distribution-models.html" rel="" target="">
 <span class="dropdown-text">A very brief introduction to species distribution models in R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./012-intro-tidyverse.html" rel="" target="">
 <span class="dropdown-text">Introduction to tidyverse packages</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./014-intro-summarizing-visualizing.html" rel="" target="">
 <span class="dropdown-text">Introduction to data summarizing and visualization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./016-intro-shiny.html" rel="" target="">
 <span class="dropdown-text">Interactive web apps with Shiny</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./017-open-street-map.qmd" rel="" target="">
 <span class="dropdown-text"></span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./018-ml-regression.html" rel="" target="">
 <span class="dropdown-text">Machine learning in R part 1: regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
  <li><a href="#workspace-organization" id="toc-workspace-organization" class="nav-link" data-scroll-target="#workspace-organization">Workspace organization</a></li>
  <li><a href="#download-data" id="toc-download-data" class="nav-link" data-scroll-target="#download-data">Download data</a></li>
  <li><a href="#reading-data-into-r-for-pca" id="toc-reading-data-into-r-for-pca" class="nav-link" data-scroll-target="#reading-data-into-r-for-pca">Reading data into R for PCA</a></li>
  </ul></li>
  <li><a href="#principal-components-analysis" id="toc-principal-components-analysis" class="nav-link" data-scroll-target="#principal-components-analysis">Principal Components Analysis</a>
  <ul class="collapse">
  <li><a href="#running-pca" id="toc-running-pca" class="nav-link" data-scroll-target="#running-pca">Running PCA</a></li>
  <li><a href="#a-brief-interpretion-of-pca-results-part-one" id="toc-a-brief-interpretion-of-pca-results-part-one" class="nav-link" data-scroll-target="#a-brief-interpretion-of-pca-results-part-one">A brief interpretion of PCA results (part one)</a></li>
  <li><a href="#plotting-pca-results" id="toc-plotting-pca-results" class="nav-link" data-scroll-target="#plotting-pca-results">Plotting PCA results</a></li>
  <li><a href="#a-brief-interpretion-of-pca-results-part-two" id="toc-a-brief-interpretion-of-pca-results-part-two" class="nav-link" data-scroll-target="#a-brief-interpretion-of-pca-results-part-two">A brief interpretion of PCA results (part two)</a></li>
  <li><a href="#final-script-for-pca-plot" id="toc-final-script-for-pca-plot" class="nav-link" data-scroll-target="#final-script-for-pca-plot">Final script for PCA plot</a></li>
  </ul></li>
  <li><a href="#discriminant-function-analysis" id="toc-discriminant-function-analysis" class="nav-link" data-scroll-target="#discriminant-function-analysis">Discriminant Function Analysis</a>
  <ul class="collapse">
  <li><a href="#reading-data-into-r-for-dfa" id="toc-reading-data-into-r-for-dfa" class="nav-link" data-scroll-target="#reading-data-into-r-for-dfa">Reading data into R for DFA</a></li>
  <li><a href="#running-dfa" id="toc-running-dfa" class="nav-link" data-scroll-target="#running-dfa">Running DFA</a></li>
  <li><a href="#plotting-dfa-results" id="toc-plotting-dfa-results" class="nav-link" data-scroll-target="#plotting-dfa-results">Plotting DFA results</a></li>
  <li><a href="#a-brief-interpretion-of-dfa-results-part-one" id="toc-a-brief-interpretion-of-dfa-results-part-one" class="nav-link" data-scroll-target="#a-brief-interpretion-of-dfa-results-part-one">A brief interpretion of DFA results (part one)</a></li>
  <li><a href="#a-brief-interpretion-of-dfa-results-part-two" id="toc-a-brief-interpretion-of-dfa-results-part-two" class="nav-link" data-scroll-target="#a-brief-interpretion-of-dfa-results-part-two">A brief interpretion of DFA results (part two)</a></li>
  <li><a href="#plotting-dfa-assignment-probabilities-advanced" id="toc-plotting-dfa-assignment-probabilities-advanced" class="nav-link" data-scroll-target="#plotting-dfa-assignment-probabilities-advanced">Plotting DFA assignment probabilities (ADVANCED)</a></li>
  <li><a href="#final-script-for-dfa-posteriors" id="toc-final-script-for-dfa-posteriors" class="nav-link" data-scroll-target="#final-script-for-dfa-posteriors">Final script for DFA posteriors</a></li>
  </ul></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources">Additional resources</a>
  <ul class="collapse">
  <li><a href="#general-multivariate-analyses" id="toc-general-multivariate-analyses" class="nav-link" data-scroll-target="#general-multivariate-analyses">General multivariate analyses:</a></li>
  <li><a href="#pca" id="toc-pca" class="nav-link" data-scroll-target="#pca">PCA</a></li>
  <li><a href="#dfa" id="toc-dfa" class="nav-link" data-scroll-target="#dfa">DFA</a></li>
  <li><a href="#installing-r-packages" id="toc-installing-r-packages" class="nav-link" data-scroll-target="#installing-r-packages">Installing R packages</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="003-intro-multivariate.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to Multivariate Statistics in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jeff Oliver </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 8, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>An introduction to using the R statistics package and the RStudio interface for multivariate statistics.</p>
<section id="learning-objectives" class="level4">
<h4 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h4>
<ol type="1">
<li>Read data from files into R</li>
<li>Run Principal Components Analysis (PCA) and graphically display results</li>
<li>Perform Discriminant Function Analysis (DFA) and interpret the results</li>
</ol>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<section id="workspace-organization" class="level3">
<h3 class="anchored" data-anchor-id="workspace-organization">Workspace organization</h3>
<p>First we need to setup our development environment. Open RStudio and create a new project via:</p>
<ul>
<li>File &gt; New Project…</li>
<li>Select ‘New Directory’</li>
<li>For the Project Type select ‘New Project’</li>
<li>For Directory name, call it something like “r-multivar” (without the quotes)</li>
<li>For the subdirectory, select somewhere you will remember (like “My Documents” or “Desktop”)</li>
</ul>
<p>We need to create two folders: ‘data’ will store the data we will be analyzing, and ‘output’ will store the results of our analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="at">path =</span> <span class="st">"data"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="at">path =</span> <span class="st">"output"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="download-data" class="level3">
<h3 class="anchored" data-anchor-id="download-data">Download data</h3>
<ul>
<li>Download data file from <a href="https://raw.githubusercontent.com/jcoliver/learn-r/gh-pages/data/otter-mandible-data.csv">https://raw.githubusercontent.com/jcoliver/learn-r/gh-pages/data/otter-mandible-data.csv</a> or <a href="https://bit.ly/otter-data">https://bit.ly/otter-data</a> (the latter just re-directs to the former). These data are a subset of those used in a study on skull morphology and diet specialization in otters <a href="http://dx.doi.org/10.1371/journal.pone.0143236">doi: 10.1371/journal.pone.0143236</a>.</li>
<li>Move the file to the data folder you created above.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/otter-mandible.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">(A) Skull morphology of <em>Lutra lutra</em>. (B) Six mandible measurements used in this lesson: m1 = mandible ramus width, m2 = mandible ramus height, m3 = moment arm temporalis, m4 = outlever at carnassal, m5 = moment arm masseter, m6 = jaw length. Adapted from <a href="https://commons.wikimedia.org/wiki/File:MSU_V2P1b_-_Lutra_lutra_skull.png">https://commons.wikimedia.org/wiki/File:MSU_V2P1b_-_Lutra_lutra_skull.png</a>.</figcaption>
</figure>
</div>
</section>
<section id="reading-data-into-r-for-pca" class="level3">
<h3 class="anchored" data-anchor-id="reading-data-into-r-for-pca">Reading data into R for PCA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/otter-mandible-data.csv"</span>, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Missing data can cause problems in downstream analyses, so we will just remove any rows that have missing data. Here we replace the original data object <code>otter</code> with one in which there are no missing values. Note, this <em>does not</em> alter the data in the original file we read into R; it only alters the data object <code>otter</code> currently in R’s memory.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(otter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And because R <em>does not</em> automatically re-number the rows when we drop those with <code>NA</code> values, we can force re-numbering via:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(otter) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p><em>Side note</em>: Before we go any further, it is important to note that the remainder of this lesson uses what is known as “base R”, or only those parts of R that come along when you download and install R. This means it does not include any code that comes from packages such as <a href="https://www.tidyverse.org/">tidyverse</a>. Users of tidyverse packages (especially ggplot2) may cringe at what you see below. It is left to the reader as an exercise to execute the plots using the superb data visualization package ggplot2. If you are so inclined, take a look at the separate lessons on <a href="https://jcoliver.github.io/learn-r/004-intro-ggplot.html">ggplot2</a> and <a href="https://jcoliver.github.io/learn-r/012-intro-tidyverse.html">tidyverse</a> for more information.</p>
</blockquote>
</section>
</section>
<section id="principal-components-analysis" class="level2">
<h2 class="anchored" data-anchor-id="principal-components-analysis">Principal Components Analysis</h2>
<p>Why PCA? Very briefly, Principal Components Analysis is a way of re-describing the variation observed in your data. It serves as a means of reducing the dimensionality of data (i.e.&nbsp;reducing the number of predictor variables) and is often used for exploratory analyses. The full rationale and mathematically underpinnings are waaaaaaaay beyond the scope of this lesson, and other resources already do a fairly good job of explaining PCA. If you want a few perspectives for a relatively novice audience, check out this <a href="http://stats.stackexchange.com/questions/2691/making-sense-of-principal-component-analysis-eigenvectors-eigenvalues">Why PCA? (or “how to explain PCA to your grandmother”)</a> thread at Stack Overflow. If you are more inclined to print media, I highly recommend B.F.J. Manly’s <em>Multivariate Statistical Methods: A primer</em> (2004), which provides an excellent introduction to a variety of multivariate statistic topics.</p>
<section id="running-pca" class="level3">
<h3 class="anchored" data-anchor-id="running-pca">Running PCA</h3>
<p>So, on to the code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pca_fit <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(<span class="at">x =</span> otter[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)], <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That’s PCA.</p>
<p>Give yourself a pat on the back.</p>
<p>But what does that code actually <em>do</em>? We pass the data to the <code>x</code> parameter, skipping the first three columns <code>[, -c(1:3)]</code> because those columns have the specimen information (species identity and accession information). We also set the <code>scale.</code> parameter to <code>TRUE</code> because we want to transform the data so each column has a mean of zero and a variance of one.</p>
<p>To look at the results, we use the <code>summary</code> command and assign the output to a variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>pca_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(pca_fit)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>(pca_summary) <span class="co"># Lists the objects produced by summary</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "center"     "importance" "rotation"   "scale"      "sdev"      
[6] "x"         </code></pre>
</div>
</div>
<p>We are interested to know (1) what are the important factors that emerge from the PCA (i.e.&nbsp;which ones explain a lot of variation) and (2) what do these factors actually say about the variation observed in our data. For (1), look at the <code>importance</code> object in the summary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pca_summary<span class="sc">$</span>importance</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            PC1       PC2       PC3       PC4       PC5
Standard deviation     2.256654 0.6219432 0.5454519 0.3255933 0.2708043
Proportion of Variance 0.848750 0.0644700 0.0495900 0.0176700 0.0122200
Cumulative Proportion  0.848750 0.9132200 0.9628000 0.9804700 0.9926900
                             PC6
Standard deviation     0.2093664
Proportion of Variance 0.0073100
Cumulative Proportion  1.0000000</code></pre>
</div>
</div>
<p>The second row, <code>Proportion of Variance</code>, shows how much variation in the data is described by each component; notice that the first component, PC1, explains the most variance, 0.8487, or 84.87% of the total variance, the second component explains the second most variance (6.45%), and so on, with each successive component explaining a lower proportion of the total variance. For the remainder of the lesson, we will focus on the first two principal components, PC1 and PC2, which together explain 91.32% of the observed variation in the skull measurements.</p>
</section>
<section id="a-brief-interpretion-of-pca-results-part-one" class="level3">
<h3 class="anchored" data-anchor-id="a-brief-interpretion-of-pca-results-part-one">A brief interpretion of PCA results (part one)</h3>
<p>But what about that variation? What are the principal components actually explaining? To address this (point 2 from above), we need to look at the loadings of the PCA. The <code>rotation</code> object from the summary call has the information we are interested in. Focus on the values in the PC1 column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pca_summary<span class="sc">$</span>rotation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         PC1         PC2         PC3         PC4        PC5        PC6
m1 0.4268529 -0.17321735  0.22703406 -0.02536558 -0.6606796 -0.5469067
m2 0.4075959  0.49503042  0.25708539 -0.50388745 -0.1654951  0.4913515
m3 0.4056830 -0.45770175  0.38536919 -0.25533585  0.6293816 -0.1268993
m4 0.3908318  0.03103549 -0.83871167 -0.30435539  0.1229400 -0.1873594
m5 0.4026960  0.56665446  0.08297005  0.60659893  0.3025684 -0.2243763
m6 0.4149336 -0.43976047 -0.15340120  0.46868237 -0.1825671  0.5982600</code></pre>
</div>
</div>
<p>Looking at the signs of the loadings, we see they are all the same (positive), thus this first component, explaining most of the variation in the measurements, is really just reflecting variation in size. That is, since all the loadings have the same sign, large values for one skull measurement generally coincide with large values for other skull measurements for this first component.</p>
<p>The second principal component is a little more interesting. Two of the variables, m1 and m4 don’t contribute much to the component (the magnitudes of their respective loadings (0.173 and 0.031) are small compared to the other four skull measurements). The remaining four indicate a shape difference, with one pair of variables having positive loadings and one pair having negative loadings. This interpretation of the second principal component would benefit greatly from a graphical representation.</p>
</section>
<section id="plotting-pca-results" class="level3">
<h3 class="anchored" data-anchor-id="plotting-pca-results">Plotting PCA results</h3>
<p>Plotting the results of a PCA can be done using a simple call to the <code>biplot</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">biplot</span>(<span class="at">x =</span> pca_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/pca-biplot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>But that figure really leaves much to be desired, and gets messier with larger sample sizes and more variables. If you want to find out more about how that figure is produced, look at the documentation for <code>biplot</code> (<code>?biplot</code>).</p>
<p>Instead, we can plot the scores of the first two principal components using the standard <code>plot</code> command, using the scores that are stored in the <code>x</code> object of <code>pca_fit</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">1</span>],</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">2</span>],</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"PC 1"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"PC 2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/pca-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Well, maybe that plot isn’t so useful either. It does help a bit if we color the points by species, though. We start by creating a small vector which only contains the species names; we’ll use this for the legend and for assigning colors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out the unique values in the 'species' column</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>species_names <span class="ot">&lt;-</span> <span class="fu">unique</span>(otter<span class="sc">$</span>species)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>species_names <span class="co"># a quick look at the values in the vector</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] A. cinerea      E. lutris       L. canadensis   P. brasiliensis
Levels: A. cinerea E. lutris L. canadensis P. brasiliensis</code></pre>
</div>
</div>
<p>We want a vector of colors, too, one for each species. Since there are four species, we have four colors:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The legend_cols vector will be used for the legend, but we still need a color vector for each <em>sample</em>. We can use the indexing of the <code>species_names</code> and <code>legend_cols</code> to create a vector which has a value for each of the points we want to plot. Here we first assign all values the same color (the first color in the <code>legend_cols</code> vector). Then we compare values in the <code>otter$species</code> column to the second, third, and fourth possible values in the <code>species_names</code> vector.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pt_cols <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x =</span> legend_cols[<span class="dv">1</span>], <span class="at">length =</span> <span class="fu">nrow</span>(otter))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">2</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">2</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">3</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">3</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">4</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Question: Why did we <em>not</em> do the assignment / comparison for the first element in <code>species_names</code> and <code>legend_cols</code>?</p>
</blockquote>
<p>And finally, we draw the plot, adding point colors through the <code>col</code> parameter and adding the legend after the plot is drawn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">1</span>],</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">2</span>],</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"PC 1"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"PC 2"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> pt_cols)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomleft"</span>, </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> species_names, </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> legend_cols, </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/pca-color-plot-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="a-brief-interpretion-of-pca-results-part-two" class="level3">
<h3 class="anchored" data-anchor-id="a-brief-interpretion-of-pca-results-part-two">A brief interpretion of PCA results (part two)</h3>
<p>Ah, now this plot is a little more interesting. Note the first principal component scores along the x-axis, and there is actually pretty clear separation among some of species. As mentioned above, this principal component is really an index of size, which we can visualize by looking at the actual skull measurements across the four species. First note the distribution of the four species along the x-axis: <em>A. cinerea</em> has the lowest values, <em>E. lutris</em> and <em>P. brasiliensis</em> have the highest values, and <em>L. canadensis</em> has values in the middle. We can use <code>boxplot</code> to show the distributions of each measurement for each species:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set-up a multi-panel graph (2 rows, 3 columns), filling row by row</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>), <span class="at">las =</span> <span class="dv">2</span>) </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot each of the six measurements in a different plot, leaving x-axis title </span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># out of the plot</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m1 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m2 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m3 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m4 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m5 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> m6 <span class="sc">~</span> species, <span class="at">data =</span> otter, <span class="at">xlab =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/pca-mfrow-plot-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Restore graphing defaults</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">las =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at these boxplots, we see that indeed, for all six measurements, <em>A. cinerea</em> has the lowest values, <em>E. lutris</em> and <em>P. brasiliensis</em> have the highest values, and <em>L. canadensis</em> has values in the middle.</p>
<p>Remember that second principal component, PC2, on the y-axis of our scatterplot:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/pca-color-plot-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>And the loadings for the first two components are:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         PC1         PC2
m1 0.4268529 -0.17321735
m2 0.4075959  0.49503042
m3 0.4056830 -0.45770175
m4 0.3908318  0.03103549
m5 0.4026960  0.56665446
m6 0.4149336 -0.43976047</code></pre>
</div>
</div>
<p>In this second principal component, as mentioned before, m1 and m4 don’t contribute much to the component (the magnitudes of their respective loadings, 0.173 and 0.031, respectively, are small compared to the other four skull measurements). The remaining four loadings indicate a shape difference, with one pair of variables having positive loadings and one pair having negative loadings. This component describes variation in the four variables: high values of PC1 correspond to high values of m2 and m5 and low values of m3 and m6, while specimens with low values of PC1 have the opposite (low m2 and m5, high m3 and m6). You can confirm this looking again at a boxplot for these values, focusing only on those four variables of interest for the two species that are differentiated along PC2, <em>E. lutris</em> and <em>P. brasiliensis</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out the data for the two species of interest</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>two_species <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"E. lutris"</span>, <span class="st">"P. brasiliensis"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>otter_two <span class="ot">&lt;-</span> otter[otter<span class="sc">$</span>species <span class="sc">%in%</span> two_species, ]</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop the levels corresponding to the two species we excluded</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>otter_two<span class="sc">$</span>species <span class="ot">&lt;-</span> <span class="fu">factor</span>(otter_two<span class="sc">$</span>species)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare colors</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red3"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>pt_cols <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x =</span> legend_cols[<span class="dv">1</span>], <span class="at">length =</span> <span class="fu">nrow</span>(otter_two))</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>pt_cols[otter_two<span class="sc">$</span>species <span class="sc">==</span> two_species[<span class="dv">2</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">2</span>]</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot m6 against m5</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> otter_two<span class="sc">$</span>m5, </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> otter_two<span class="sc">$</span>m6, </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"m5"</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"m6"</span>,</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> pt_cols)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> two_species, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> legend_cols, <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/two-species-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Considering the scores of PC2, <em>P. brasilensis</em> had low values, while <em>E. lutris</em> had high values. If we consider the loadings for just m5 and m6 on PC2 (0.567 and -0.44, respectively), the plot above shows what we expect: specimens with high values of PC2 (i.e.&nbsp;those of <em>E. lutris</em>), should have relatively low values of m5 and high values of m6; this contrasts with specimens with low values of PC2 (i.e.&nbsp;those of <em>P. brasilensis</em>), which are characterized by high values of m5 and low values of m6. The second principal component is thus describing variation in <em>relative</em>, not absolute, sizes of these four different measurements.</p>
</section>
<section id="final-script-for-pca-plot" class="level3">
<h3 class="anchored" data-anchor-id="final-script-for-pca-plot">Final script for PCA plot</h3>
<p>Our script for performing Principal Components Analysis and graphing the first two components should look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PCA on otter jaw measurements</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Jeff Oliver</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># jcoliver@email.arizona.edu</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2016-11-18</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/otter-mandible-data.csv"</span>, </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with NA</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(otter)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Renumber rows</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(otter) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Run PCA</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>pca_fit <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(<span class="at">x =</span> otter[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)], <span class="at">scale. =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>pca_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(pca_fit)</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting results</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull out the unique values in the 'species' column for legend</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>species_names <span class="ot">&lt;-</span> <span class="fu">unique</span>(otter<span class="sc">$</span>species)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a vector of colors for the *legend*</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a vector of colors for the actual *plot*, based on values in the </span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="co"># 'species' column and the legend colors vector. This vector has one element </span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="co"># corresponding to each row of the otter data frame. </span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>pt_cols <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x =</span> legend_cols[<span class="dv">1</span>], <span class="at">length =</span> <span class="fu">nrow</span>(otter))</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">2</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">2</span>]</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">3</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">3</span>]</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> species_names[<span class="dv">4</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">4</span>]</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the first two components</span></span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">1</span>],</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> pca_fit<span class="sc">$</span>x[, <span class="dv">2</span>],</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"PC 1"</span>,</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"PC 2"</span>,</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> pt_cols)</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomleft"</span>, </span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> species_names, </span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> legend_cols, </span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
</section>
<section id="discriminant-function-analysis" class="level2">
<h2 class="anchored" data-anchor-id="discriminant-function-analysis">Discriminant Function Analysis</h2>
<p>Principal Components Analysis is useful to describe variation, especially when groups of samples are not known <em>a priori</em>. However, when the groups <em>are</em> known, one can use Discriminant Function Analysis, DFA, to see if the these groups can be differentiated based on a suite of variables. We will use the same otter data to see if we can differentiate among the four species based on the jaw measurements.</p>
<section id="reading-data-into-r-for-dfa" class="level3">
<h3 class="anchored" data-anchor-id="reading-data-into-r-for-dfa">Reading data into R for DFA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/otter-mandible-data.csv"</span>, </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with NA</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(otter)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Renumber rows</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(otter) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="running-dfa" class="level3">
<h3 class="anchored" data-anchor-id="running-dfa">Running DFA</h3>
<p>To run a DFA, we use a function in the <code>MASS</code> library, an additional package of R functions. To load a package for use in R, we use the <code>library</code> function and include the name of the package (see below if you want to learn more about <a href="#installing-r-packages">installing packages</a>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"MASS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And we run DFA with a call to <code>lda</code> indicating which column contains our <em>a priori</em> groups in via the <code>formula</code> parameter. In this case, we pass <code>formula = species ~ m1 + m2 + m3 + m4 + m5 + m6</code>, which means <code>species</code> contains our grouping variable and the ‘m’ variables are the predictors in the analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run DFA, allowing equal probability assignment for each of four groups</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>lda_fit <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> species <span class="sc">~</span> m1 <span class="sc">+</span> m2 <span class="sc">+</span> m3 <span class="sc">+</span> m4 <span class="sc">+</span> m5 <span class="sc">+</span> m6,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> otter,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">prior =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">/</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We also indicate that assignment to each species is equally likely (25%) by setting the prior probabilities for group membership through the <code>prior</code> parameter.</p>
</section>
<section id="plotting-dfa-results" class="level3">
<h3 class="anchored" data-anchor-id="plotting-dfa-results">Plotting DFA results</h3>
<p>We can plot DFA results in a similar fashion as we did for PCA results. In this case we plot the scores for the first and second discriminant functions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get individual values based on lda model and original measurements</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>lda_predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object =</span> lda_fit,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">newdata =</span> otter)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up colors for each point, based on a priori identifications</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>pt_cols <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="at">x =</span> legend_cols[<span class="dv">1</span>], <span class="at">length =</span> <span class="fu">nrow</span>(otter))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">2</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">2</span>]</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">3</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">3</span>]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>pt_cols[otter<span class="sc">$</span>species <span class="sc">==</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">4</span>]] <span class="ot">&lt;-</span> legend_cols[<span class="dv">4</span>]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot scores for first (lda_predict$x[, 1]) and second (lda_predict$x[, 2]) </span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co"># discriminant functions</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> lda_predict<span class="sc">$</span>x[, <span class="dv">1</span>], </span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> lda_predict<span class="sc">$</span>x[, <span class="dv">2</span>], </span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"LDA1"</span>, </span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"LDA2"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> pt_cols)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, </span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species), </span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>, </span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> legend_cols, </span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/dfa-plot-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="a-brief-interpretion-of-dfa-results-part-one" class="level3">
<h3 class="anchored" data-anchor-id="a-brief-interpretion-of-dfa-results-part-one">A brief interpretion of DFA results (part one)</h3>
<p>Let’s take a look at how well the DFA did in classifying the specimens. In order to do this, we are going to call <code>lda</code> again, this time passing an additional argument to the <code>CV</code> parameter. By setting <code>CV = TRUE</code>, R will perform cross-validation on the model and provide posterior probabilities of group membership in the <code>posterior</code> object returned by <code>lda</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>lda_fit <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> species <span class="sc">~</span> m1 <span class="sc">+</span> m2 <span class="sc">+</span> m3 <span class="sc">+</span> m4 <span class="sc">+</span> m5 <span class="sc">+</span> m6, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> otter, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">prior =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">/</span><span class="dv">4</span>, </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">CV =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To see how well the DFA does in categorizing each specimen, we use <code>table</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(otter<span class="sc">$</span>species, lda_fit<span class="sc">$</span>class, <span class="at">dnn =</span> <span class="fu">c</span>(<span class="st">"a priori"</span>, <span class="st">"assignment"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 assignment
a priori          A. cinerea E. lutris L. canadensis P. brasiliensis
  A. cinerea              23         0             0               0
  E. lutris                0        67             0               0
  L. canadensis            0         0            42               0
  P. brasiliensis          0         0             0              17</code></pre>
</div>
</div>
<p>In this case, we passed <code>table</code> two vectors:</p>
<ul>
<li>The <em>a priori</em> species identification of each sample, which is stored in <code>otter$species</code></li>
<li>The <em>a posteriori</em> assignment of each sample from the DFA, stored in <code>lda_fit$class</code></li>
</ul>
<p>We also passed a value to the <code>dnn</code> parameter, which is used to label the table (“dnn” stands for <em>dimnames names</em>. Yes, that’s right, <em>dimnames names</em>. Seems repetitive to me, too). The first row of the table shows how the specimens identified as <em>A. cinerea</em> were assigned in the DFA - all were correctly assigned to <em>A. cinerea</em>. What should jump out at you in this table is that <em>all</em> specimens’ DFA assignments match their <em>a priori</em> identifications.</p>
</section>
<section id="a-brief-interpretion-of-dfa-results-part-two" class="level3">
<h3 class="anchored" data-anchor-id="a-brief-interpretion-of-dfa-results-part-two">A brief interpretion of DFA results (part two)</h3>
<p>But let’s take a <em>closer</em> look at the results. The first six rows show the assignment probabilities for six specimens:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lda_fit<span class="sc">$</span>posterior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  A. cinerea    E. lutris L. canadensis P. brasiliensis
1  0.9988772 1.120591e-18  1.122777e-03    3.037108e-26
2  0.9999948 3.072667e-24  5.151834e-06    1.895663e-25
3  0.9999945 8.582366e-25  5.476448e-06    2.046930e-31
4  0.9999890 7.775338e-24  1.103396e-05    1.730129e-33
5  0.9999747 4.875762e-23  2.527825e-05    1.873520e-30
6  0.9996107 3.958971e-19  3.893433e-04    1.778982e-29</code></pre>
</div>
</div>
<p>The <code>lda_fit$posterior</code> matrix holds the posterior probability of assignment to each of the four species for each row of data in the original <code>otter</code> data. The first row indicates the probabilities that the first observation in <code>otter</code> is assigned to each species. For this first observation, the only non-negligible assignment probability is to <em>A. cinerea</em>. For this data set, most observations are assigned with high probability to a single group.</p>
<p>However, some probabilities are not so trivial. Look at the values for row 88 (rounding to three decimal places):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(lda_fit<span class="sc">$</span>posterior[<span class="dv">88</span>, ], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A. cinerea       E. lutris   L. canadensis P. brasiliensis 
          0.000           0.543           0.457           0.000 </code></pre>
</div>
</div>
<p>How can we identify those with ambiguous assignments? We could go row-by-row to see which rows have assignment ambiguity, but R wasn’t developed so we could do things by hand. So first we define our cutoff for the posterior probability. In this case, we’ll say any sample with a posterior probability less than 0.95 has an ambiguous assignment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set our cutoff value for what we call unambiguous</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>minimum_prob <span class="ot">&lt;-</span> <span class="fl">0.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then create a matrix of assignments based on this cutoff by comparing the values in <code>lda_fit$posterior</code> to our cutoff value, <code>minimum_prob</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A new matrix of logicals, with TRUE for all cells with </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># posterior prob &gt; minimum_prob</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>unambiguous <span class="ot">&lt;-</span> lda_fit<span class="sc">$</span>posterior <span class="sc">&gt;</span> minimum_prob</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Taking a look at the first few rows of the <code>unambiguous</code> object, we see it is filled with <code>TRUE</code> and <code>FALSE</code> values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(unambiguous)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  A. cinerea E. lutris L. canadensis P. brasiliensis
1       TRUE     FALSE         FALSE           FALSE
2       TRUE     FALSE         FALSE           FALSE
3       TRUE     FALSE         FALSE           FALSE
4       TRUE     FALSE         FALSE           FALSE
5       TRUE     FALSE         FALSE           FALSE
6       TRUE     FALSE         FALSE           FALSE</code></pre>
</div>
</div>
<p>A row where the assignment probabilities for <strong>every</strong> group was below the threshold should only have values of FALSE. Take our example from row 88 as described above. The posterior probabilities were:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(lda_fit<span class="sc">$</span>posterior[<span class="dv">88</span>, ], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A. cinerea       E. lutris   L. canadensis P. brasiliensis 
          0.000           0.543           0.457           0.000 </code></pre>
</div>
</div>
<p>And the corresponding values in our <code>unambiguous</code> object are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>unambiguous[<span class="dv">88</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     A. cinerea       E. lutris   L. canadensis P. brasiliensis 
          FALSE           FALSE           FALSE           FALSE </code></pre>
</div>
</div>
<p>Because we are only interested in those samples where assignment was ambiguous, we need to identify those rows where <strong>all</strong> the values are <code>FALSE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># New vector indicating whether sample had any assignment greater than </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># minimum_prob</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>unambiguous_rows <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X =</span> unambiguous, <span class="at">MARGIN =</span> <span class="dv">1</span>, <span class="at">FUN =</span> <span class="st">"any"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The converse (i.e. vector indicating samples with *no* assignment greater </span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># than minimum_prob)</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>ambiguous_rows <span class="ot">&lt;-</span> <span class="sc">!</span>unambiguous_rows</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Use this to retrieve sample information for those rows and probabilities</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>ambiguous_results <span class="ot">&lt;-</span> otter[ambiguous_rows, <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)]</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>ambiguous_results <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ambiguous_results, lda_fit<span class="sc">$</span>posterior[ambiguous_rows, ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This new data frame, <code>ambiguous_results</code> contains the posterior probabilities for all those samples with no assignment probabilities higher than the <code>minimum_prob</code> threshold. It also has the metadata associated with those samples, which we extracted from the original <code>otter</code> data frame. Looking at this data frame, we see there were 5 samples could not be unambiguously assigned to a group (assuming a posterior probability threshold of 0.95):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show only those samples which didn't have high assignment probability to any </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># group</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>ambiguous_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          species museum accession   A. cinerea    E. lutris L. canadensis
74      E. lutris  Burke     34537 6.428127e-07 7.785889e-01     0.2214105
88      E. lutris  Burke     34558 2.828393e-08 5.428820e-01     0.4571180
93  L. canadensis  Burke     21177 9.692098e-02 1.938878e-13     0.9030790
130 L. canadensis   TAMU      2142 3.049221e-01 2.712423e-07     0.6950776
131 L. canadensis   TAMU      4212 4.434483e-01 3.973644e-09     0.5565517
    P. brasiliensis
74     2.281819e-18
88     3.939901e-18
93     1.977415e-23
130    2.356272e-16
131    2.442044e-24</code></pre>
</div>
</div>
</section>
<section id="plotting-dfa-assignment-probabilities-advanced" class="level3">
<h3 class="anchored" data-anchor-id="plotting-dfa-assignment-probabilities-advanced">Plotting DFA assignment probabilities (ADVANCED)</h3>
<p>One way to visualize how well the analysis performed at distinguishing among the groups is to plot the posterior probabilities for each sample. These can be done with a stacked bar graph (much like the graphs used to visualize <a href="http://pritchardlab.stanford.edu/structure.html">STRUCTURE</a> results). The first thing we need is a two-dimensional matrix of the posterior probabilities, with each sample corresponding to a <em>column</em>. The <code>lda_fit$posteriors</code> object has samples in rows, so we can use transpose, <code>t</code>, to exchange the rows and columns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>posteriors <span class="ot">&lt;-</span> <span class="fu">t</span>(lda_fit<span class="sc">$</span>posterior)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And we can plot these posteriors with <code>barplot</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/barplot-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hmmm…that’s a lot of gray. Let’s start by eliminating space between bars and getting rid of the borders:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">space =</span> <span class="dv">0</span>,</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/barplot-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>And now we can add some color, making an adjustment to the x-axis (via <code>xlim</code>) so the legend shows up <em>outside</em> the plot area:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">space =</span> <span class="dv">0</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">45</span>),</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> legend_cols,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/barplot-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The legend still overlaps the plot, so we’ll need to pass some additional parameters to the legend maker.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">space =</span> <span class="dv">0</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">45</span>),</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> legend_cols,</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species),</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">x =</span> <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">55</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">xpd =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/barplot-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The last thing we want is to show the <em>a priori</em> assignments of the samples. This requires some creativity on our part. The code below assumes that the original data being fed into the <code>lda</code> function were already sorted by species. Two new vectors, <code>tick_pos</code> and <code>label_pos</code>, are used to add the <em>a priori</em> identification information to the x-axis.</p>
<ul>
<li><code>tick_pos</code> will draw five vertical tick marks on the x-axis, to serve as delimiters between species.</li>
<li><code>label_pos</code> vector determines where to put the labels on the x-axis.</li>
</ul>
<p>Because this isn’t a standard way of labeling an axis, we tell R to skip labeling the x-axis in the <code>barplot</code> call (<code>xaxt = 'n'</code>), and instead, label the axis after the plot is drawn, with a pair of calls to the <code>axis</code> function. I’ll leave it as an exercise for you to determine how <code>tick_pos</code> and <code>label_pos</code> are calculated (hint: documentation for <code>match</code> and <code>rev</code> will be helpful). Finally, we will need to add some more vertical space in our plot to prevent the species names on the x-axis from being cut off; we use the <code>par</code> function to temporarily change the margins of our plot, adding some space to the bottom margin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Besides the first element, which is 0, the remaining values in the vector we </span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># created are the cutoff points for each species. The second element takes the </span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># value of the position of the last occurrence of the first species, the third </span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># element takes the value of the position of the last occurrence of the second </span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># species, and so on.</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>tick_pos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">1</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">2</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">3</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">4</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>label_pos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">floor</span>((tick_pos[<span class="dv">2</span>] <span class="sc">-</span> tick_pos[<span class="dv">1</span>]) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">3</span>] <span class="sc">-</span> tick_pos[<span class="dv">2</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">2</span>]),</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">4</span>] <span class="sc">-</span> tick_pos[<span class="dv">3</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">3</span>]),</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">5</span>] <span class="sc">-</span> tick_pos[<span class="dv">4</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">4</span>]))</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Store graphics defaults</span></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>mar_default <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="dv">1</span> <span class="co"># from par documentation</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar_default <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)) <span class="co"># add space to bottom margin</span></span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>,</span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">space =</span> <span class="dv">0</span>,</span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>,</span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">'n'</span>,</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">45</span>),</span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> legend_cols,</span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species),</span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a>        <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">x =</span> <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">55</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">xpd =</span> <span class="cn">TRUE</span>))</span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Add tick marks</span></span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a>     <span class="at">at =</span> tick_pos, </span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="cn">FALSE</span>)</span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Add axis labels</span></span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, </span>
<span id="cb51-38"><a href="#cb51-38" aria-hidden="true" tabindex="-1"></a>     <span class="at">at =</span> label_pos, </span>
<span id="cb51-39"><a href="#cb51-39" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species), </span>
<span id="cb51-40"><a href="#cb51-40" aria-hidden="true" tabindex="-1"></a>     <span class="at">tick =</span> <span class="cn">FALSE</span>, </span>
<span id="cb51-41"><a href="#cb51-41" aria-hidden="true" tabindex="-1"></a>     <span class="fu">par</span>(<span class="at">las =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="003-intro-multivariate_files/figure-html/barplot-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Restore graphics defaults</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar_default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="final-script-for-dfa-posteriors" class="level3">
<h3 class="anchored" data-anchor-id="final-script-for-dfa-posteriors">Final script for DFA posteriors</h3>
<p>The final script for running the DFA and creating the barplot of posterior probabilities would then be:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DFA on otter jaw measurements</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Jeff Oliver</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># jcoliver@email.arizona.edu</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2016-11-18</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in data</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/otter-mandible-data.csv"</span>, </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop rows with NA</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>otter <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(otter)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Renumber rows</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(otter) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Load MASS library</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"MASS"</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Run DFA</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>lda_fit <span class="ot">&lt;-</span> <span class="fu">lda</span>(<span class="at">formula =</span> species <span class="sc">~</span> m1 <span class="sc">+</span> m2 <span class="sc">+</span> m3 <span class="sc">+</span> m4 <span class="sc">+</span> m5 <span class="sc">+</span> m6, </span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> otter, </span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a>               <span class="at">prior =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">/</span><span class="dv">4</span>, </span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>               <span class="at">CV =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Setup vectors for labeling x-axis with a priori assignments. </span></span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Besides the first element, which is 0, the remaining values in the vector we </span></span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a><span class="co"># created are the cutoff points for each species. The second element takes the </span></span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a><span class="co"># value of the position of the last occurrence of the first species, the third </span></span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a><span class="co"># element takes the value of the position of the last occurrence of the second </span></span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a><span class="co"># species, and so on.</span></span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>tick_pos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, </span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">1</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">2</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">3</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>, </span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>              <span class="fu">nrow</span>(otter) <span class="sc">-</span> <span class="fu">match</span>(<span class="fu">levels</span>(otter<span class="sc">$</span>species)[<span class="dv">4</span>], <span class="fu">rev</span>(otter<span class="sc">$</span>species)) <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a>label_pos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">floor</span>((tick_pos[<span class="dv">2</span>] <span class="sc">-</span> tick_pos[<span class="dv">1</span>]) <span class="sc">/</span> <span class="dv">2</span>),</span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">3</span>] <span class="sc">-</span> tick_pos[<span class="dv">2</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">2</span>]),</span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">4</span>] <span class="sc">-</span> tick_pos[<span class="dv">3</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">3</span>]),</span>
<span id="cb53-40"><a href="#cb53-40" aria-hidden="true" tabindex="-1"></a>               <span class="fu">floor</span>((tick_pos[<span class="dv">5</span>] <span class="sc">-</span> tick_pos[<span class="dv">4</span>]) <span class="sc">/</span> <span class="dv">2</span> <span class="sc">+</span> tick_pos[<span class="dv">4</span>]))</span>
<span id="cb53-41"><a href="#cb53-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-42"><a href="#cb53-42" aria-hidden="true" tabindex="-1"></a>legend_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"green4"</span>, <span class="st">"cyan3"</span>, <span class="st">"red3"</span>) </span>
<span id="cb53-43"><a href="#cb53-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-44"><a href="#cb53-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Store graphics defaults</span></span>
<span id="cb53-45"><a href="#cb53-45" aria-hidden="true" tabindex="-1"></a>mar_default <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="dv">1</span> <span class="co"># from par documentation</span></span>
<span id="cb53-46"><a href="#cb53-46" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar_default <span class="sc">+</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)) <span class="co"># add space to bottom margin</span></span>
<span id="cb53-47"><a href="#cb53-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-48"><a href="#cb53-48" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(posteriors,</span>
<span id="cb53-49"><a href="#cb53-49" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Posterior Probability"</span>,</span>
<span id="cb53-50"><a href="#cb53-50" aria-hidden="true" tabindex="-1"></a>        <span class="at">space =</span> <span class="dv">0</span>,</span>
<span id="cb53-51"><a href="#cb53-51" aria-hidden="true" tabindex="-1"></a>        <span class="at">border =</span> <span class="cn">NA</span>,</span>
<span id="cb53-52"><a href="#cb53-52" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">'n'</span>,</span>
<span id="cb53-53"><a href="#cb53-53" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">45</span>),</span>
<span id="cb53-54"><a href="#cb53-54" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> legend_cols,</span>
<span id="cb53-55"><a href="#cb53-55" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.text =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species),</span>
<span id="cb53-56"><a href="#cb53-56" aria-hidden="true" tabindex="-1"></a>        <span class="at">args.legend =</span> <span class="fu">list</span>(<span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">x =</span> <span class="fu">ncol</span>(posteriors) <span class="sc">+</span> <span class="dv">55</span>, <span class="at">y =</span> <span class="fl">0.6</span>, <span class="at">xpd =</span> <span class="cn">TRUE</span>))</span>
<span id="cb53-57"><a href="#cb53-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Add x-axis labels</span></span>
<span id="cb53-58"><a href="#cb53-58" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> tick_pos, <span class="at">labels =</span> <span class="cn">FALSE</span>) <span class="co"># tick marks</span></span>
<span id="cb53-59"><a href="#cb53-59" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> label_pos, <span class="at">labels =</span> <span class="fu">levels</span>(otter<span class="sc">$</span>species), <span class="at">tick =</span> <span class="cn">FALSE</span>, <span class="fu">par</span>(<span class="at">las =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.8</span>))</span>
<span id="cb53-60"><a href="#cb53-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-61"><a href="#cb53-61" aria-hidden="true" tabindex="-1"></a><span class="co"># Restore graphics defaults</span></span>
<span id="cb53-62"><a href="#cb53-62" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> mar_default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
</section>
<section id="additional-resources" class="level2">
<h2 class="anchored" data-anchor-id="additional-resources">Additional resources</h2>
<section id="general-multivariate-analyses" class="level3">
<h3 class="anchored" data-anchor-id="general-multivariate-analyses">General multivariate analyses:</h3>
<ul>
<li>Manly, B.F.J. 2004. <em>Multivariate Statistical Methods: a primer</em>. Chapman &amp; Hall, Boca Raton. For University of Arizona affiliates, there is an online version of this book at <a href="https://arizona-primo.hosted.exlibrisgroup.com/permalink/f/evot53/01UA_ALMA21407247900003843">https://arizona-primo.hosted.exlibrisgroup.com/permalink/f/evot53/01UA_ALMA21407247900003843</a>.</li>
</ul>
</section>
<section id="pca" class="level3">
<h3 class="anchored" data-anchor-id="pca">PCA</h3>
<ul>
<li><a href="http://www.statmethods.net/advstats/factor.html">Quick-R page on PCA</a></li>
<li><a href="https://www.r-bloggers.com/computing-and-visualizing-pca-in-r/">Visualizing PCA results from r-bloggers</a></li>
<li><a href="https://www.r-bloggers.com/performing-principal-components-regression-pcr-in-r/">Principal Components Regression from r-bloggers</a></li>
<li><a href="http://stats.stackexchange.com/questions/2691/making-sense-of-principal-component-analysis-eigenvectors-eigenvalues">Why PCA? (or “how to explain PCA to your grandmother”)</a></li>
</ul>
</section>
<section id="dfa" class="level3">
<h3 class="anchored" data-anchor-id="dfa">DFA</h3>
<ul>
<li><a href="http://www.statmethods.net/advstats/discriminant.html">Quick-R page on DFA</a></li>
<li><a href="https://www.r-bloggers.com/computing-and-visualizing-lda-in-r/">R-bloggers DFA with visualization</a></li>
</ul>
<hr>
</section>
<section id="installing-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="installing-r-packages">Installing R packages</h3>
<p>Note that if a package is not installed on your machine, a call to <code>library</code> will throw an error, indicating the package has to be installed first. For example, if we were to load a package called <code>mustelid</code> without installing it first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mustelid"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in library("mustelid"): there is no package called 'mustelid'</code></pre>
</div>
</div>
<p>So how do I install packages? you ask. With <code>install.packages</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"mustelid"</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"mustelid"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(note there is no R package called “mustelid”, so no matter how hard you try, this example will always end in failure)</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2024, Jeffrey Oliver
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 Deed</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jcoliver">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>