<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jeff Oliver">
<meta name="dcterms.date" content="2024-05-16">

<title>learn-r - Introduction to data summarizing and visualization</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EF6ZJH0577"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-EF6ZJH0577', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">learn-r</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resources.html"> 
<span class="menu-text">Additional Resources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a>
  <ul class="collapse">
  <li><a href="#the-tools-r-and-rstudio" id="toc-the-tools-r-and-rstudio" class="nav-link" data-scroll-target="#the-tools-r-and-rstudio">The tools: R and RStudio</a></li>
  <li><a href="#preparing-our-workplace" id="toc-preparing-our-workplace" class="nav-link" data-scroll-target="#preparing-our-workplace">Preparing our workplace</a></li>
  <li><a href="#getting-the-data" id="toc-getting-the-data" class="nav-link" data-scroll-target="#getting-the-data">Getting the data</a></li>
  </ul></li>
  <li><a href="#data-in-r" id="toc-data-in-r" class="nav-link" data-scroll-target="#data-in-r">Data in R</a>
  <ul class="collapse">
  <li><a href="#data-outside-r" id="toc-data-outside-r" class="nav-link" data-scroll-target="#data-outside-r">Data <em>outside</em> R</a></li>
  <li><a href="#data-in-r-1" id="toc-data-in-r-1" class="nav-link" data-scroll-target="#data-in-r-1">Data in R</a></li>
  <li><a href="#quality-assurance" id="toc-quality-assurance" class="nav-link" data-scroll-target="#quality-assurance">Quality Assurance</a></li>
  </ul></li>
  <li><a href="#cleaning-up" id="toc-cleaning-up" class="nav-link" data-scroll-target="#cleaning-up">Cleaning up</a>
  <ul class="collapse">
  <li><a href="#missing-data" id="toc-missing-data" class="nav-link" data-scroll-target="#missing-data">Missing data</a></li>
  <li><a href="#subsetting-data" id="toc-subsetting-data" class="nav-link" data-scroll-target="#subsetting-data">Subsetting data</a></li>
  </ul></li>
  <li><a href="#what-about-that-spreadsheet-file" id="toc-what-about-that-spreadsheet-file" class="nav-link" data-scroll-target="#what-about-that-spreadsheet-file">What about that spreadsheet file?</a></li>
  <li><a href="#summarizing-data" id="toc-summarizing-data" class="nav-link" data-scroll-target="#summarizing-data">Summarizing data</a>
  <ul class="collapse">
  <li><a href="#using-summary" id="toc-using-summary" class="nav-link" data-scroll-target="#using-summary">Using <code>summary</code></a></li>
  <li><a href="#summary-statistics-for-groups" id="toc-summary-statistics-for-groups" class="nav-link" data-scroll-target="#summary-statistics-for-groups">Summary statistics for groups</a></li>
  <li><a href="#summary-statistics-made-easier" id="toc-summary-statistics-made-easier" class="nav-link" data-scroll-target="#summary-statistics-made-easier">Summary statistics made easier</a></li>
  <li><a href="#get-cover-for-each-familyplot" id="toc-get-cover-for-each-familyplot" class="nav-link" data-scroll-target="#get-cover-for-each-familyplot">Get % cover for each family/plot</a></li>
  </ul></li>
  <li><a href="#visualizing-data" id="toc-visualizing-data" class="nav-link" data-scroll-target="#visualizing-data">Visualizing data</a>
  <ul class="collapse">
  <li><a href="#first-rule-of-plots" id="toc-first-rule-of-plots" class="nav-link" data-scroll-target="#first-rule-of-plots">First rule of plots</a></li>
  <li><a href="#the-ggplot2-package" id="toc-the-ggplot2-package" class="nav-link" data-scroll-target="#the-ggplot2-package">The ggplot2 package</a></li>
  <li><a href="#code-it-second" id="toc-code-it-second" class="nav-link" data-scroll-target="#code-it-second">Code it second</a></li>
  <li><a href="#telling-the-story" id="toc-telling-the-story" class="nav-link" data-scroll-target="#telling-the-story">Telling the story</a></li>
  </ul></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources">Additional resources</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="014-intro-summarizing-visualizing.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Introduction to data summarizing and visualization</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jeff Oliver </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The R programming language provides many tools for data analysis and visualization, but all the options can be daunting. This lesson provides an introduction to wrangling data in R and using graphics to tell a story with data.</p>
<section id="learning-objectives" class="level4">
<h4 class="anchored" data-anchor-id="learning-objectives">Learning objectives</h4>
<ol type="1">
<li>Understand the difference between files and R objects</li>
<li>Modify data for proper data hygiene</li>
<li>Summarize information from raw data</li>
<li>Visualize data to convey information</li>
</ol>
<hr>
</section>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting started</h2>
<section id="the-tools-r-and-rstudio" class="level3">
<h3 class="anchored" data-anchor-id="the-tools-r-and-rstudio">The tools: R and RStudio</h3>
<p>For this lesson, we will use the R programming language in the RStudio environment. RStudio provides a convenient interface for working with files and packages in R. If you have not done so already, install R and RStudio; details can be found on the <a href="https://jcoliver.github.io/learn-r/000-setup-instructions.html">installation page</a>.</p>
</section>
<section id="preparing-our-workplace" class="level3">
<h3 class="anchored" data-anchor-id="preparing-our-workplace">Preparing our workplace</h3>
<p>Key to successful programming is organization. In RStudio, we use Projects to organize our work (a “Project” is really just a fancy name for a folder that contains all our files). For this lesson, we’ll create a new project through the File menu (File &gt; New Project). In the first dialog, select “New Directory”, and select “New Project” in the second dialog. Next you’ll be prompted to provide a directory name. This will be the name of our project, so we should give it an informative name. For this lesson, we will be using data from vegetation surveys of <a href="https://www.nps.gov/tuma/index.htm">Tumacacori National Historical Park</a>; so give our directory a descriptive name, like “vegetation”. We need also to tell RStudio where to put the lesson on our computer; for this lesson, we will place the folder on our Desktop, so it is easy to find. In your own work, you may find it better to place project folders in your Documents folder.</p>
<p>The last thing we need to do to set up our workspace is to use file organization that reinforces best practices. In general, there should be a one-way flow of information: we take information from <em>data</em> and write code to produce <em>output</em>. We want to avoid any output from messing up our data, so we create separate folders for each. We want to create two folders, one for our data and one for any output, which may include results of statistical analyses or data visualization. In the R console,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"data"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"output"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="getting-the-data" class="level3">
<h3 class="anchored" data-anchor-id="getting-the-data">Getting the data</h3>
<p>We are going to use vegetation survey data from the Tumacacori National Historical Park. These data are based on several surveys and are available through the National Park Service’s <a href="https://irma.nps.gov/DataStore/Reference/Profile/2233448">Integrated Resource Management Applications Data Store</a>.</p>
<p>We can use R to directly download the data from the web. In the R console, enter:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="at">url =</span> <span class="st">"https://tinyurl.com/tnhp-data"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">destfile =</span> <span class="st">"data/tumacacori-vegetation.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(You can also download the file manually by entering <a href="https://tinyurl.com/tnhp-data">https://tinyurl.com/tnhp-data</a> into a web browser’s address bar.)</p>
<p>Note if you click on the data folder in your project (there should be a file browser in the lower-right corner of your RStudio window), you should see a single file, “tumacacori-vegetation.csv”, that shows up as 31.5 KB. If you do not see that file, or if the file size is listed as 0 KB, try downloading the file again, making sure you spelled the URL and destination file name correctly.</p>
<hr>
</section>
</section>
<section id="data-in-r" class="level2">
<h2 class="anchored" data-anchor-id="data-in-r">Data in R</h2>
<section id="data-outside-r" class="level3">
<h3 class="anchored" data-anchor-id="data-outside-r">Data <em>outside</em> R</h3>
<p>We are going to start by looking at those data we downloaded in a spreadsheet program like Excel or <a href="https://www.libreoffice.org/">LibreOffice</a>. Open your spreadsheet program and open the file we just downloaded. We can see the data are organized in columns and rows. This is a good example of what is known as “tidy data” where there is one observation per row and one type of data per column. In these data, each row corresponds to a single plant species in a single plot, and the columns have different data about that species, including the family name and the percent cover in that plot.</p>
<p>Take a moment to look at those data but don’t change any of the values in the cells. Close the file, and make sure <em>not</em> to save any changes to the file.</p>
</section>
<section id="data-in-r-1" class="level3">
<h3 class="anchored" data-anchor-id="data-in-r-1">Data in R</h3>
<p>We are going to work with those same data in R. To do so we will need to read the data in to R’s memory, but first we are going to start a script so all the steps we take for data analyses are going to be saved in one place. Make a new script through the File menu, via File &gt; New File… &gt; R Script. We’ll start by adding a little bit of information at the beginning of the script:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Tumacacori vegetation</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Jeffrey C. Oliver</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># jcoliver@email.arizona.edu</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2019-09-06</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that RStudio is also telling us that we have unsaved changes: the text in the tab is red and there is a little asterisk up by the file name (which is probably “Untitled1”, which should also be a clue). We should save this file via Ctrl-S (Window or Linux) or Cmd-S (MacOS), giving it a short but descriptive name. We’ll use tumacacori-plots.R.</p>
<p>Now we are finally going to read data into R. When you opened the file in Excel you might have noticed that it has the file extension “csv”, which stands for Comma-Separated Values. The CSV file format is common for data tables and has the benefit that it can be easily ready by many programs, which is not always the case for .xls and .xlsx files. To read the data into R, we use the <code>read.csv</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/tumacacori-vegetation.csv"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The statement shows typical syntax for an R command. From an abstract perspective, most R statements look like:</p>
<p><span class="math display">\[
Variable \enspace Name \leftarrow Function \enspace Name (Function \enspace Arguments)
\]</span></p>
<p>The <em>function</em> (<code>read.csv</code>) is given two pieces of information, or <em>arguments</em>:</p>
<ol type="1">
<li><code>file</code> which tells R where the file is located (in this case, in the data folder)</li>
<li><code>stringsAsFactors</code> which tells R to treat text data as categorical data</li>
</ol>
<p>The data in the file are read into R, then stored in a <em>variable</em> called <code>plant_data</code>.</p>
</section>
<section id="quality-assurance" class="level3">
<h3 class="anchored" data-anchor-id="quality-assurance">Quality Assurance</h3>
<p>Whenever we start writing a new script, we <em>always</em> want to make sure the data are being read in correctly. When we are doing this initial quality check, we don’t necessarily need to record all the commands we type, so we can use the R console to type commands. We’ll start with <code>head</code> which shows the first six rows of data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(plant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Plot_Code            Field_Name           Common_Name        Family
1 TUMC_IP01     Acacia constricta     whitethorn acacia      Fabaceae
2 TUMC_IP01      Acacia greggii          catclaw acacia      Fabaceae
3 TUMC_IP01  Amaranthus palmeri            carelessweed Amaranthaceae
4 TUMC_IP01   Aristida ternipes             spidergrass       Poaceae
5 TUMC_IP01 Bidens leptocephala   fewflower beggarticks    Asteraceae
6 TUMC_IP01   Boerhavia spicata     creeping spiderling Nyctaginaceae
  Species_Code Percent_Cover     Leaf_Type    Leaf_Phenology Community
1       ACACON          30.0 Microphyllous Drought-deciduous Shrubland
2       ACAGRE          30.0 Microphyllous Drought-deciduous Shrubland
3       AMAPAL           3.0 Microphyllous Drought-deciduous Shrubland
4       ARITER           0.5 Microphyllous Drought-deciduous Shrubland
5       BIDLEP          18.0 Microphyllous Drought-deciduous Shrubland
6       BOESPI           8.0 Microphyllous Drought-deciduous Shrubland</code></pre>
</div>
</div>
<p>Similarly, the <code>tail</code> function shows the last six rows of data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(plant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Plot_Code               Field_Name            Common_Name         Family
286 TUMC_IPS4 Eragrostis lehmanniana        Lehmann lovegrass        Poaceae
287 TUMC_IPS4   Erioneuron avenaceum    shortleaf woollygrass        Poaceae
288 TUMC_IPS4    Opuntia engelmannii             cactus apple      Cactaceae
289 TUMC_IPS4      Prosopis velutina          velvet mesquite       Fabaceae
290 TUMC_IPS4           Salsola kali          Russian thistle Chenopodiaceae
291 TUMC_IPS4                     &lt;NA&gt; Unknown Perennial Forb           &lt;NA&gt;
    Species_Code Percent_Cover     Leaf_Type    Leaf_Phenology Community
286       ERALEH           0.5 Microphyllous Drought-deciduous Shrubland
287       ERIAVE           0.5 Microphyllous Drought-deciduous Shrubland
288       OPUENG           0.5 Microphyllous Drought-deciduous Shrubland
289       PROVEL          50.5 Microphyllous Drought-deciduous Shrubland
290       SALKAL           0.5 Microphyllous Drought-deciduous Shrubland
291       UNKFOR           8.0 Microphyllous Drought-deciduous Shrubland</code></pre>
</div>
</div>
<p>Note in the output of <code>tail</code> there are rows with <code>&lt;NA&gt;</code> values. In R, <code>NA</code> has a special meaning: it indicates missing values in the data. We’ll deal with that in a bit, but remember that missing data may require some special handling in R.</p>
<p>One more useful function is <code>str</code>, which stands for “structure”:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(plant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   291 obs. of  9 variables:
 $ Plot_Code     : Factor w/ 22 levels "TUMC_IP01","TUMC_IP02",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Field_Name    : Factor w/ 71 levels "Acacia constricta",..: 1 2 5 9 12 14 18 37 44 45 ...
 $ Common_Name   : Factor w/ 74 levels "Annual Forb",..: 73 15 14 57 31 20 55 12 72 16 ...
 $ Family        : Factor w/ 26 levels "Acanthaceae",..: 12 12 3 20 4 17 20 7 15 12 ...
 $ Species_Code  : Factor w/ 74 levels "ACACON","ACAGRE",..: 1 2 7 11 14 16 19 39 46 47 ...
 $ Percent_Cover : num  30 30 3 0.5 18 8 18 0.5 0.5 3 ...
 $ Leaf_Type     : Factor w/ 3 levels "Broad-leaved",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ Leaf_Phenology: Factor w/ 3 levels "Cold-deciduous",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ Community     : Factor w/ 5 levels "Forest","Shrubland",..: 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
</div>
<p>The output of <code>str</code> shows the size of the data, in terms of number of rows and columns, and the type of data in each column.</p>
<hr>
</section>
</section>
<section id="cleaning-up" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-up">Cleaning up</h2>
<p>Rarely are data “ready to go” when they are read into R. The data we are using are going to require two adjustments: removal of rows with missing data and a selection of only a portion of the data.</p>
<section id="missing-data" class="level3">
<h3 class="anchored" data-anchor-id="missing-data">Missing data</h3>
<p>To remove rows that have missing data, we use the <code>na.omit</code> function. Before we do, though, look at the “Environment” tab of your workspacek. There should be a row for <code>plant_data</code> that indicates the size of our data set. In this case, it should show “291 obs. of 9 variables”, indicating we have 291 rows of data, with 9 columns. Now let’s drop those rows with missing data, putting this command in the script file, not the R console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(plant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Look again at the Environment tab. There should only be 287 obs. because we removed those rows with missing data. The number of columns should not change at all. One thing we are going to do now is to start commenting our code. We use the pound or hash sign (<code>#</code>) to tell R that we are writing a comment that should not be interpreted as code. For that line we just wrote, we are going to add a little note about <em>why</em> we did what we did.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Do not want rows with missing data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(plant_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="subsetting-data" class="level3">
<h3 class="anchored" data-anchor-id="subsetting-data">Subsetting data</h3>
<p>The dataset include observations of 26 different plant families at the plots. For our purposes, we are going to focus on a few of the families that make up most of these communities, namely the legumes (Fabaceae), grasses (Poaceae), mustards (Brassicaceae), and amaranths (Amaranthaceae).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Only focus on four families</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>families_keep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Fabaceae"</span>, <span class="st">"Poaceae"</span>, <span class="st">"Brassicaceae"</span>, <span class="st">"Amaranthaceae"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new data with only four families</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> plant_data[plant_data<span class="sc">$</span>Family <span class="sc">%in%</span> families_keep, ]</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-level data in the Family column</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>subset_data<span class="sc">$</span>Family <span class="ot">&lt;-</span> <span class="fu">factor</span>(subset_data<span class="sc">$</span>Family)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In those three lines, we:</p>
<ul>
<li>Created a list of the names of the families we are interested in,</li>
<li>Made a new variable called <code>subset_data</code> and stored the data for only those four families, and</li>
<li>“Re-leveled” the data in the Family column (no need to worry too much about what this means now, it will just make plotting easier later on).</li>
</ul>
<p>Look again at your Environment tab, you should see another item listed, this one called <code>subset_data</code>. It <em>should</em> have 164 rows (observations). If it doesn’t, check your work to make sure you spelled all the family names correctly.</p>
</section>
</section>
<section id="what-about-that-spreadsheet-file" class="level2">
<h2 class="anchored" data-anchor-id="what-about-that-spreadsheet-file">What about that spreadsheet file?</h2>
<p>So we’ve done some manipulations to the data, dropping rows with missing data and creating a subset for four families. Did that do anything to the original spreadsheet file? Open the file in your spreadsheet program (like Excel or LibreOffice) and take a look. If you look towards the bottom, you can see that those rows with NA are still there. Compare this with the output of <code>tail(plant_data)</code>. Note the <code>plant_data</code> in R does not have the rows with NA values because we removed them with <code>na.omit</code> above. This demonstrates that modfiying data in R <em>does not change the data in the original data files</em>. Files are only changed when we explicity tell R to write changes to the hard drive. Since we do not want those changes written to our original data file, we are <em>not</em> going to have R write any data to the files.</p>
<hr>
</section>
<section id="summarizing-data" class="level2">
<h2 class="anchored" data-anchor-id="summarizing-data">Summarizing data</h2>
<p>We would like to get some summary data from our data, and R provides functions for making this easy.</p>
<section id="using-summary" class="level3">
<h3 class="anchored" data-anchor-id="using-summary">Using <code>summary</code></h3>
<p>The <code>summary</code> function works on data frames (which is how R stores spreadsheets). It provides a little bit of information about each of the columns of data. For columns that have categorical data, like <code>Common_Name</code>, it tells us how many rows have each category. For columns with numerical data, it provides some statistics, such as the mean, median, minimum, and maximum.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(subset_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Plot_Code                      Field_Name               Common_Name
 TUMC_IP12: 13   Prosopis velutina       :21   velvet mesquite     :21  
 TUMC_IP15: 11   Acacia greggii          :19   catclaw acacia      :19  
 TUMC_IP05: 10   Amaranthus palmeri      :17   carelessweed        :17  
 TUMC_IP14: 10   Bouteloua curtipendula  :14   sideoats grama      :14  
 TUMC_IP20: 10   Descurainia pinnata     :14   western tansymustard:14  
 TUMC_IP02:  9   Setaria                 :12   bristlegrass        :12  
 (Other)  :101   (Other)                 :67   (Other)             :67  
           Family    Species_Code Percent_Cover                     Leaf_Type  
 Amaranthaceae:17   PROVEL :21    Min.   : 0.50   Broad-leaved           : 11  
 Brassicaceae :18   ACAGRE :19    1st Qu.: 0.50   Broad-leaved herbaceous:  4  
 Fabaceae     :53   AMAPAL :17    Median : 3.00   Microphyllous          :149  
 Poaceae      :76   BOUCUR :14    Mean   :12.73                                
                    DESPIN :14    3rd Qu.:18.00                                
                    SETAR  :12    Max.   :86.00                                
                    (Other):67                                                 
           Leaf_Phenology             Community 
 Cold-deciduous   : 11    Forest           :15  
 Drought-deciduous:149    Shrubland        :70  
 Herb - annual    :  4    Wooded Herbaceous: 4  
                          Wooded Shrubland :71  
                          Woodland         : 4  
                                                
                                                </code></pre>
</div>
</div>
<p>Looking at this output, we see, for instance, there are 21 rows with data for velvet mesquite. We also see the mean percent cover is 12.73 across all plots and species.</p>
</section>
<section id="summary-statistics-for-groups" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-for-groups">Summary statistics for groups</h3>
<p>But what if we wanted information about certain groups of data? For example we might want the mean and standard deviation of percent cover for a particular species. We can calculate those statistics for all species with the <code>mean</code> and <code>sd</code> functions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract summary statistics for all species in subsetted data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>cover_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>cover_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(subset_data<span class="sc">$</span>Percent_Cover)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see the values of each of these by typing in the variable name alone into the R console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>cover_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.72561</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cover_sd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.48287</code></pre>
</div>
</div>
<p>But how do we get these statistics for a single species, say velvet mesquite? We can perform a data subset <em>within</em> the calls to <code>mean</code> and <code>sd</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and standard deviation for mesquite alone</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>mesquite_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"velvet mesquite"</span>])</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>mesquite_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"velvet mesquite"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the commands above, we still used <code>mean</code> and <code>sd</code> on the <code>Percent_Cover</code> column but here we <em>only</em> used those rows where the value in the <code>Common_Name</code> column was “velvet mesquite”. Typing the variable names into the R console will show us the statistics for velvet mesquite.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mesquite_mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27.07143</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mesquite_sd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.14077</code></pre>
</div>
</div>
<p>Note that R is case-sensitive, meaning that lower-case letters and upper-case letters are different in R. If we changed the calculation for the mean from</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>mesquite_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"velvet mesquite"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>to (capitalizing the “V” and the “M”):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mesquite_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"Velvet Mesquite"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>the result will be <code>NaN</code> which stands for “Not a Number”. This is because there are zero rows with the common name of “Velvet Mesquite”, and the mean of nothing is not definable.</p>
<p>What if you wanted means and standard deviations for each species? You could copy and paste the code, changing the variable name and species name for every species, but since there are 32 different common names in these data, that would be tedious and a great way to make a mistake. Thankfully, there are additional packages in R that make this much easier.</p>
</section>
<section id="summary-statistics-made-easier" class="level3">
<h3 class="anchored" data-anchor-id="summary-statistics-made-easier">Summary statistics made easier</h3>
<p>To get these summary statistics for all species, we are going to use a third-party package. What does that mean, “third-party”? When we think of software, there are generally two parties: the one that wrote the software and the one that uses the software. In this case, the R Core Team wrote the R software and we are the second party, the users of R. Third-party packages are those written by someone other than the authors of the original software. R is especially amenable to third-party development and some of the most widely used packages in R were developed by teams other than the R Core Team. Importantly, if we are using third-party R packages, we need to take two steps: first we need to <strong>install</strong> the package, second we need to <strong>load</strong> the package’s functions into memory. The first (installation) only has to happen once on your machine; the second (loading into memory) has to happen every time you use R.</p>
<p>We are going to use the <a href="https://dplyr.tidyverse.org/">dplyr</a> package for summarizing our data. To install dplyr:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now that the package is installed, we can load it into memory with the <code>library</code> command. When using third-party packages, we generally add <code>library</code> commands to the start of the script, so anyone reading our script can tell which, if any, additional packages the script requires to run.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
</div>
<p>Now we can use dplyr functions to generate summary statistics for <em>each</em> species. Here we use the <code>group_by</code> function to essentially create a separate pile of data for each species, then, for each “pile”, calculate the mean and standard deviation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and standard deviation for each species separately</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Common_Name) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_cover =</span> <span class="fu">mean</span>(Percent_Cover),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_cover =</span> <span class="fu">sd</span>(Percent_Cover))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we consider the above code using English, it is easier to understand if we replace all the pipes (<code>%&gt;%</code>) with the word “then”:</p>
<pre><code>summary_stats &lt;- subset_data, then
  group_by(Common_Name), then
  summarize(mean_cover = mean(Percent_Cover),
            sd_cover = sd(Percent_Cover))</code></pre>
<p>Or, using words only,</p>
<pre><code>Make a new variable called "summary_stats", take the subset_data, then
  make a separate group of data for each Common_Name, then
  calculate the mean and standard deviation of Percent_Cover and store them 
      in columns called "mean_cover" and "sd_cover" respectively.</code></pre>
<p>We can also add this explanation to our code through the use of comments:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and standard deviation for each species separately</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make a separate group of data for each Common_Name</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Common_Name) <span class="sc">%&gt;%</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the mean and standard deviation of Percent_Cover and store them </span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    in columns called "mean_cover" and "sd_cover" respectively</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_cover =</span> <span class="fu">mean</span>(Percent_Cover),</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_cover =</span> <span class="fu">sd</span>(Percent_Cover))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see these summary stats by typing the variable name, <code>summary_stats</code> into the R console:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>summary_stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 32 × 3
   Common_Name      mean_cover sd_cover
   &lt;fct&gt;                 &lt;dbl&gt;    &lt;dbl&gt;
 1 Bermudagrass           8        0   
 2 big sacaton           13.6     21.7 
 3 bristlegrass           1.54     1.29
 4 broomcorn millet       3       NA   
 5 bush muhly            14.3     11.3 
 6 cane bluestem          0.5     NA   
 7 carelessweed          20.9     18.7 
 8 catclaw acacia        19.2     17.5 
 9 catclaw mimosa         1.75     1.77
10 cliff muhly           13        7.07
# ℹ 22 more rows</code></pre>
</div>
</div>
</section>
<section id="get-cover-for-each-familyplot" class="level3">
<h3 class="anchored" data-anchor-id="get-cover-for-each-familyplot">Get % cover for each family/plot</h3>
<p>Ultimately, we would like to look at how much cover there is for each plant family in the Tumacacori plots. Right now the data are shown for each <em>species</em>, but we would like to know how much of the plant cover corresponds to each <em>family</em> . We’ll use the dplyr package again for summarizing data, but this time we are going to group by several levels: first by the plot, then by family, then by the community.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate familiy-level total percent cover for each plot separately</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>family_data <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Plot_Code, Family, Community) <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Family_Percent_Cover =</span> <span class="fu">sum</span>(Percent_Cover))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Plot_Code', 'Family'. You can override
using the `.groups` argument.</code></pre>
</div>
</div>
<p>Once again, thinking about this code in English, we can replace all the pipes (<code>%&gt;%</code>) with the word “then”:</p>
<pre><code>Make a new variable called family_data, take the subset_data, then
  make a separate group of data for each Plot_Code, break those groups up 
    into smaller groups, one for each Family, divide those groups into separate 
    groups for Community, then
  add up all the values in the Percent_Cover column and store it 
      in a column called "Family_Percent_Cover"</code></pre>
<p>If we look at these data, we can see we now have total percent cover for each family:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(family_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
# Groups:   Plot_Code, Family [6]
  Plot_Code Family        Community        Family_Percent_Cover
  &lt;fct&gt;     &lt;fct&gt;         &lt;fct&gt;                           &lt;dbl&gt;
1 TUMC_IP01 Amaranthaceae Shrubland                         3  
2 TUMC_IP01 Fabaceae      Shrubland                        71.5
3 TUMC_IP01 Poaceae       Shrubland                        48  
4 TUMC_IP02 Amaranthaceae Wooded Shrubland                 63  
5 TUMC_IP02 Brassicaceae  Wooded Shrubland                  0.5
6 TUMC_IP02 Fabaceae      Wooded Shrubland                 14.5</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="visualizing-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-data">Visualizing data</h2>
<p>When we are using data to tell a story, often we use a visualization in order to make a point. In this case, we are especially interested in looking at how the percent cover of different families of plants differs (or doesn’t differ) among the different plant communities. For example, we would be interested to know if the percent cover of the Fabaceae, which includes mesquites and acacias, differs between those plots categorized as forest and those plots categorized as shrubland.</p>
<section id="first-rule-of-plots" class="level3">
<h3 class="anchored" data-anchor-id="first-rule-of-plots">First rule of plots</h3>
<p>Whenever we want to visualize data, it is almost best to draw it out by hand. This makes it easy to evaluate different graphical representations of data. So to start, take a moment to consider the data in <code>family_data</code> and how it could be visualized. Keep in mind the question above about percent cover differences among plant communities. Don’t worry about exact values, just think about how a drawing could illustrate the point.</p>
</section>
<section id="the-ggplot2-package" class="level3">
<h3 class="anchored" data-anchor-id="the-ggplot2-package">The ggplot2 package</h3>
<p>In order to visualize the data in R, we are going to use the ggplot2 package. Like we did for the dplyr package, we will first need to install the package:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As we did with the dplyr package, we use the <code>library</code> function to load the functions into memory (remember, this should go at the beginning of your script):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="code-it-second" class="level3">
<h3 class="anchored" data-anchor-id="code-it-second">Code it second</h3>
<p>Now that we have the ggplot2 package installed, we are going to make a boxplot of the data. Boxplots are especially good for comparing values of different categories. Here we are going to create a boxplot for percent cover, with different communities shown on the x-axis. So here we go.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of family-level data</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>cover_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> family_data, </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Family_Percent_Cover)) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cover_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s break down that code:</p>
<ul>
<li><code>ggplot</code> is the main function for creating graphics in the ggplot2 package, we start by passing it two pieces of information:
<ul>
<li><code>data</code> tells R which data to use, in this case we are using the percent cover sums we stored in <code>family_data</code></li>
<li>we use the <code>mapping</code> argument to tell R which variable to put on the x-axis (<code>Community</code>) and which variable to put on the y-axis (<code>Family_Percent_Cover</code>)</li>
</ul></li>
<li>We also have to tell R <em>how</em> to plot the data. Because we are interested in creating a boxplot, we use the command <code>geom_boxplot</code>.</li>
<li>Finally, we tell R to draw the plot with the <code>print</code> command. That is, we created an entire plot object and stored it in the variable <code>cover_plot</code>. We use the <code>print</code> command to actually see the plot.</li>
</ul>
<p>And here is what it looks like:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-intro-summarizing-visualizing_files/figure-html/simple-boxplot-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="telling-the-story" class="level3">
<h3 class="anchored" data-anchor-id="telling-the-story">Telling the story</h3>
<p>That’s a fine start, but if we are interested in looking at differences among the families, we need an easy way of telling the families apart. We can do this in the <code>mapping</code> argument of the <code>ggplot</code> command by indicating that the shapes should be filled with different colors, according to value in the <code>Family</code> column:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of family-level data</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>cover_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> family_data, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Family_Percent_Cover,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Family)) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cover_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-intro-summarizing-visualizing_files/figure-html/color-families-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Look at the Wooded Herbaceous and Woodland - they’re just lines. Why? We can see the counts in each category using the <code>table</code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(family_data<span class="sc">$</span>Family, family_data<span class="sc">$</span>Community)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                Forest Shrubland Wooded Herbaceous Wooded Shrubland Woodland
  Amaranthaceae      2         7                 1                7        0
  Brassicaceae       2         4                 1                8        0
  Fabaceae           3         8                 1                8        1
  Poaceae            3         8                 1                8        1</code></pre>
</div>
</div>
<p>Since we only have those single plots for Wooded Herbaceous and Woodland, we should probably exclude them from our plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Too few observations in two communities, so remove them</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>family_data <span class="ot">&lt;-</span> family_data[<span class="sc">!</span>(family_data<span class="sc">$</span>Community <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Wooded Herbaceous"</span>, <span class="st">"Woodland"</span>)), ]</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of family-level data</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>cover_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> family_data, </span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Family_Percent_Cover,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Family)) <span class="sc">+</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cover_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-intro-summarizing-visualizing_files/figure-html/remove-communities-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we only have those three communities. We would also like to rearrange our x-axis so the different categories of communities have an increasing number of trees, reading left to right. That is, we want the left-most community to be Shrubland, the middle community to be Wooded Shrubland, and the right-most community to be Forest. We do this by making a slight tweak to the data, where we “re-level” the categories in the <code>Community</code> column of our data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-order levels of Community so they plot in desired order</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>family_data<span class="sc">$</span>Community <span class="ot">&lt;-</span> <span class="fu">factor</span>(family_data<span class="sc">$</span>Community,</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Shrubland"</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                                              <span class="st">"Wooded Shrubland"</span>, </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                                              <span class="st">"Forest"</span>))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of family-level data</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>cover_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> family_data, </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Family_Percent_Cover,</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Family)) <span class="sc">+</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cover_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="014-intro-summarizing-visualizing_files/figure-html/releveled-communities-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, we can save the plot to a file using the <code>ggsave</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">plot =</span> cover_plot, <span class="at">filename =</span> <span class="st">"output/family-cover-plot.pdf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This saves the file in the “output” folder with the name “family-cover-plot.pdf”.</p>
<p>Our final script would look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting Tumacacori vegetation</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Jeffrey C. Oliver</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># jcoliver@email.arizona.edu</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2019-09-06</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Libraries required for data wrangling and plotting</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">"data/tumacacori-vegetation.csv"</span>,</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Do not want rows with missing data</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>plant_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(plant_data)</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Only focus on four families</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>families_keep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Fabaceae"</span>, <span class="st">"Poaceae"</span>, <span class="st">"Brassicaceae"</span>, <span class="st">"Amaranthaceae"</span>)</span>
<span id="cb53-18"><a href="#cb53-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-19"><a href="#cb53-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new data with only four families</span></span>
<span id="cb53-20"><a href="#cb53-20" aria-hidden="true" tabindex="-1"></a>subset_data <span class="ot">&lt;-</span> plant_data[plant_data<span class="sc">$</span>Family <span class="sc">%in%</span> families_keep, ]</span>
<span id="cb53-21"><a href="#cb53-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-22"><a href="#cb53-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-level data in the Family column</span></span>
<span id="cb53-23"><a href="#cb53-23" aria-hidden="true" tabindex="-1"></a>subset_data<span class="sc">$</span>Family <span class="ot">&lt;-</span> <span class="fu">factor</span>(subset_data<span class="sc">$</span>Family)</span>
<span id="cb53-24"><a href="#cb53-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-25"><a href="#cb53-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate summary statistics for all species in subsetted data</span></span>
<span id="cb53-26"><a href="#cb53-26" aria-hidden="true" tabindex="-1"></a>cover_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover)</span>
<span id="cb53-27"><a href="#cb53-27" aria-hidden="true" tabindex="-1"></a>cover_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(subset_data<span class="sc">$</span>Percent_Cover)</span>
<span id="cb53-28"><a href="#cb53-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-29"><a href="#cb53-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and standard deviation for mesquite alone</span></span>
<span id="cb53-30"><a href="#cb53-30" aria-hidden="true" tabindex="-1"></a>mesquite_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"velvet mesquite"</span>])</span>
<span id="cb53-31"><a href="#cb53-31" aria-hidden="true" tabindex="-1"></a>mesquite_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(subset_data<span class="sc">$</span>Percent_Cover[subset_data<span class="sc">$</span>Common_Name <span class="sc">==</span> <span class="st">"velvet mesquite"</span>])</span>
<span id="cb53-32"><a href="#cb53-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-33"><a href="#cb53-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and standard deviation for each species separately</span></span>
<span id="cb53-34"><a href="#cb53-34" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb53-35"><a href="#cb53-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># make a separate group of data for each Common_Name</span></span>
<span id="cb53-36"><a href="#cb53-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Common_Name) <span class="sc">%&gt;%</span></span>
<span id="cb53-37"><a href="#cb53-37" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the mean and standard deviation of Percent_Cover and store them </span></span>
<span id="cb53-38"><a href="#cb53-38" aria-hidden="true" tabindex="-1"></a>  <span class="co">#    in columns called "mean_cover" and "sd_cover" respectively</span></span>
<span id="cb53-39"><a href="#cb53-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_cover =</span> <span class="fu">mean</span>(Percent_Cover),</span>
<span id="cb53-40"><a href="#cb53-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_cover =</span> <span class="fu">sd</span>(Percent_Cover))</span>
<span id="cb53-41"><a href="#cb53-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-42"><a href="#cb53-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate familiy-level total percent cover for each plot separately</span></span>
<span id="cb53-43"><a href="#cb53-43" aria-hidden="true" tabindex="-1"></a>family_data <span class="ot">&lt;-</span> subset_data <span class="sc">%&gt;%</span></span>
<span id="cb53-44"><a href="#cb53-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Plot_Code, Family, Community) <span class="sc">%&gt;%</span></span>
<span id="cb53-45"><a href="#cb53-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Family_Percent_Cover =</span> <span class="fu">sum</span>(Percent_Cover))</span>
<span id="cb53-46"><a href="#cb53-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-47"><a href="#cb53-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Too few observations in two communities, so remove them</span></span>
<span id="cb53-48"><a href="#cb53-48" aria-hidden="true" tabindex="-1"></a>family_data <span class="ot">&lt;-</span> family_data[<span class="sc">!</span>(family_data<span class="sc">$</span>Community <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Wooded Herbaceous"</span>, <span class="st">"Woodland"</span>)), ]</span>
<span id="cb53-49"><a href="#cb53-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-50"><a href="#cb53-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-order levels of Community so they plot in desired order</span></span>
<span id="cb53-51"><a href="#cb53-51" aria-hidden="true" tabindex="-1"></a>family_data<span class="sc">$</span>Community <span class="ot">&lt;-</span> <span class="fu">factor</span>(family_data<span class="sc">$</span>Community,</span>
<span id="cb53-52"><a href="#cb53-52" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Shrubland"</span>, <span class="st">"Wooded Shrubland"</span>, <span class="st">"Forest"</span>))</span>
<span id="cb53-53"><a href="#cb53-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-54"><a href="#cb53-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of family-level data</span></span>
<span id="cb53-55"><a href="#cb53-55" aria-hidden="true" tabindex="-1"></a>cover_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> family_data, </span>
<span id="cb53-56"><a href="#cb53-56" aria-hidden="true" tabindex="-1"></a>                     <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Community, <span class="at">y =</span> Family_Percent_Cover,</span>
<span id="cb53-57"><a href="#cb53-57" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fill =</span> Family)) <span class="sc">+</span></span>
<span id="cb53-58"><a href="#cb53-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb53-59"><a href="#cb53-59" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cover_plot)</span>
<span id="cb53-60"><a href="#cb53-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-61"><a href="#cb53-61" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="at">plot =</span> cover_plot, <span class="at">filename =</span> <span class="st">"output/family-cover-plot.pdf"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
</section>
<section id="additional-resources" class="level2">
<h2 class="anchored" data-anchor-id="additional-resources">Additional resources</h2>
<ul>
<li>Official <a href="http://docs.ggplot2.org/current/">ggplot documentation</a></li>
<li>A handy <a href="https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf">cheatsheet for ggplot</a></li>
<li>A <a href="https://jcoliver.github.io/learn-r/014-intro-summarizing-visualizing.pdf">PDF version</a> of this lesson</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Copyright 2024, Jeffrey Oliver
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://creativecommons.org/licenses/by/4.0/">
<p>CC BY 4.0 Deed</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jcoliver">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>