name: Test workflow 2

on:
  schedule:
    - cron: '30 5 * * 1,3'

jobs:
  test-print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Message from workflow test"
